---
# tasks file for docker

- name: Cloning blog repo
  git:
    repo: 'https://github.com/dcna-io/dcna.dev.git'
    dest: '/opt/dcna'

- name: Create nginx config directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/dcna/nginx
    - /opt/dcna/nginx/conf.d

- name: Copying the conf file
  copy:
    src: 'dcna.conf'
    dest: '/opt/dcna/nginx/conf.d'

- name: Build the docker image
  docker_image:
    path: '/opt/dcna'
    name: 'dcna'

- name: Run the container
  docker_container:
    name: dcna.dev
    image: dcna
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/dcna/nginx/conf.d/:/etc/nginx/conf.d/
      - /etc/letsencrypt/archive/dcna.io:/etc/letsencrypt/live/dcna.io

- name: Create/Update the DNS record
  gcp_dns_resource_record_set:
    name: dcna.dev.
    managed_zone: dcna
    type: A
    ttl: 600
    target:
    - {{ ansible_default_ipv4.address }}
    project: "{{ gcp_project }}"
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_auth }}"
    state: present

